DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;

CREATE TABLE users (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    email VARCHAR(30) NOT NULL,
    pwd VARCHAR(30) NOT NULL
);

CREATE TABLE products ( 
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(60) NOT NULL,
    descrip MEDIUMTEXT NOT NULL,
    price DECIMAL NOT NULL,
    category VARCHAR(30) NOT NULL,
    loc VARCHAR(30) NOT NULL,
    created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by INTEGER,
    CONSTRAINT fk_create FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
); 